version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: setup db"
          command: docker-compose run web bundle exec rails db:create db:migrate
      - run:
          name: "before_test: compile webpacker"
          command: docker-compose run web bundle exec rails assets:precompile
      - run:
          name: test
          command: docker-compose run web bundle exec rspec
      - run:
          name: docker-compose down
          command: docker-compose down
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # see: https://devcenter.heroku.com/articles/container-registry-and-runtime#using-a-ci-cd-platform
      - add_ssh_keys:
         fingerprints:
           - "62:90:5c:61:d6:47:c5:93:da:1f:d5:f7:69:7b:28:0e"
      - run:
          name: ssh connection
          command: ssh ${USER_NAME}@${HOST_NAME}
      - run:
          name: Deploy Master to AWS
          command: 'cd SushiSagashi && git pull origin master'
      - run:
          name: AWS db migrate
          command: 'docker-compose -f docker-compose.production.yml run web rails db:migrate'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
